---
- name: Fetch Kubernetes kubeconfig from cluster
  hosts: cp
  gather_facts: false
  vars:
    remote_kubeconfig_path: "/etc/kubernetes/admin.conf"  # Путь к kubeconfig на удалённом узле
    local_kubeconfig_dir: ".kube"  # Локальная директория для kubeconfig
    local_kubeconfig_file: "{{ local_kubeconfig_dir }}/config"  # Полный путь к локальному kubeconfig

  tasks:
    - name: Ensure local .kube directory exists
      delegate_to: localhost
      file:
        path: "{{ local_kubeconfig_dir }}"
        state: directory
        mode: '0755'

    - name: Fetch kubeconfig from remote node
      fetch:
        src: "{{ remote_kubeconfig_path }}"
        dest: "/tmp/kubeconfig_{{ inventory_hostname }}"
        flat: yes
      register: fetched_kubeconfig

    - name: Move kubeconfig to local .kube/config
      delegate_to: localhost
      copy:
        src: "/tmp/kubeconfig_{{ inventory_hostname }}"
        dest: "{{ local_kubeconfig_file }}"
        mode: '0600'
      when: fetched_kubeconfig is succeeded

    - name: Remove temporary kubeconfig file
      delegate_to: localhost
      file:
        path: "/tmp/kubeconfig_{{ inventory_hostname }}"
        state: absent
      when: fetched_kubeconfig is succeeded

    - name: Set KUBECONFIG environment variable (Optional)
      delegate_to: localhost
      lineinfile:
        path: "{{ lookup('env','HOME') }}/.bashrc"
        regexp: '^export KUBECONFIG='
        line: "export KUBECONFIG={{ local_kubeconfig_file }}"
      when: fetched_kubeconfig is succeeded

    - name: Reload shell to apply KUBECONFIG (Optional)
      delegate_to: localhost
      shell: source ~/.bashrc
      when: fetched_kubeconfig is succeeded
